# Generated by Django 5.2.3 on 2025-07-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_sale_productsale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-sale_date'], 'verbose_name': 'Sale'},
        ),
    ]
