# Generated by Django 5.2.3 on 2025-07-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_fix_product_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
